import { Card, Header, Screen } from "@/components/app-ui";
import { useAppSelector } from "@/hooks/redux-hooks/useAppSelector";
import { useCreateTenantApiKeyMutation, useCreateWebhookMutation, useDeleteTenantApiKeyMutation, useDeleteWebhookMutation, useGetTenantApiKeysQuery, useGetWebhooksQuery, useUpdateWebhookMutation } from "@/services/api/remoteApi";
import { MaterialIcons } from "@expo/vector-icons";
import { useState } from "react";
import { Alert, Modal, ScrollView, Switch, Text, TextInput, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

const EVENTS = [["order.created", "New POS sale"], ["order.completed", "Sale completed"], ["expense.created", "New expense"], ["store_setting.created", "Setting created"], ["store_setting.updated", "Setting updated"]] as const;

export default function IntegrationsScreen() {
  const user = useAppSelector((state) => state.auth.user);
  const { data: hooksData, isFetching: hooksLoading, refetch: refetchHooks } = useGetWebhooksQuery({ page: 1, limit: 100 });
  const { data: keysData, isFetching: keysLoading, refetch: refetchKeys } = useGetTenantApiKeysQuery();
  const [createHook, hookState] = useCreateWebhookMutation(); const [updateHook] = useUpdateWebhookMutation(); const [deleteHook] = useDeleteWebhookMutation();
  const [createKey, keyState] = useCreateTenantApiKeyMutation(); const [deleteKey] = useDeleteTenantApiKeyMutation();
  const [tab, setTab] = useState<"webhooks" | "keys">("webhooks"); const [modal, setModal] = useState<"webhook" | "key" | "guide" | null>(null);
  const [name, setName] = useState(""); const [url, setUrl] = useState(""); const [secret, setSecret] = useState(""); const [events, setEvents] = useState<string[]>(["order.created"]);
  const hooks = (hooksData as any)?.webhooks ?? []; const keys = Array.isArray(keysData) ? keysData as any[] : (keysData as any)?.apiKeys ?? [];
  const error = (title: string, value: any) => Alert.alert(title, value?.data?.message || value?.message || "Please try again.");
  const open = (kind: "webhook" | "key") => { setName(""); setUrl(""); setSecret(""); setEvents(["order.created"]); setModal(kind); };
  const confirm = (title: string, action: () => Promise<void>) => Alert.alert(title, "This cannot be undone.", [{ text: "Cancel", style: "cancel" }, { text: "Continue", style: "destructive", onPress: () => void action().catch((e) => error("Action failed", e)) }]);
  const submit = async () => { try { if (!name.trim()) throw new Error("Enter a name."); if (modal === "webhook") { if (!/^https:\/\//i.test(url) || !events.length) throw new Error("Use an HTTPS URL and select at least one event."); await createHook({ name: name.trim(), url: url.trim(), secret: secret.trim() || undefined, events }).unwrap(); setModal(null); await refetchHooks(); } else { if (!user?.id) throw new Error("Your user account is unavailable."); const result: any = await createKey({ userId: user.id, name: name.trim(), permissions: ["READ", "WRITE"] }).unwrap(); setModal(null); await refetchKeys(); Alert.alert("Copy the secret now", `Key\n${result.apiKey?.key}\n\nSecret\n${result.apiKey?.secret}\n\nThis secret is shown once. Store it in your server secret manager.`); } } catch (e) { error(modal === "webhook" ? "Webhook not created" : "API key not created", e); } };
  return <Screen><SafeAreaView className="flex-1"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 32 }}>
    <Header eyebrow="Admin workspace" title="Integrations" subtitle="Connect POS events to your own secure server." right={<TouchableOpacity className="rounded-full bg-sky-500/15 p-2" onPress={() => setModal("guide")}><MaterialIcons name="help-outline" size={20} color="#7dd3fc" /></TouchableOpacity>} />
    <Card className="mb-5 border-sky-500/20 bg-sky-500/10"><View className="flex-row items-start"><MaterialIcons name="shield" size={22} color="#7dd3fc" /><View className="ml-3 flex-1"><Text className="font-bold text-sky-100">For server integrations only</Text><Text className="mt-1 text-xs leading-5 text-sky-200/80">Never put a key or signing secret in a POS device, website, or source code.</Text><TouchableOpacity className="mt-3 self-start" onPress={() => setModal("guide")}><Text className="text-xs font-bold text-sky-300">Read setup guide →</Text></TouchableOpacity></View></View></Card>
    <View className="mb-5 flex-row rounded-2xl bg-slate-900 p-1.5">{([ ["webhooks", "Webhooks", "hub"], ["keys", "API keys", "key"] ] as const).map(([value, label, icon]) => <TouchableOpacity key={value} onPress={() => setTab(value)} className={`flex-1 flex-row items-center justify-center rounded-xl py-3 ${tab === value ? "bg-sky-400" : ""}`}><MaterialIcons name={icon} size={17} color={tab === value ? "#082f49" : "#94a3b8"} /><Text className={`ml-2 text-sm font-bold ${tab === value ? "text-slate-950" : "text-slate-400"}`}>{label}</Text></TouchableOpacity>)}</View>
    {tab === "webhooks" ? <><Section title="Event deliveries" text="Send signed JSON when POS activity occurs." add="Add webhook" onPress={() => open("webhook")} />{hooksLoading ? <Loading /> : hooks.length ? hooks.map((hook: any) => <Card key={hook.id} className="mb-3"><View className="flex-row items-start"><View className={`rounded-2xl p-2.5 ${hook.isActive ? "bg-emerald-400/15" : "bg-slate-800"}`}><MaterialIcons name="hub" size={20} color={hook.isActive ? "#6ee7b7" : "#94a3b8"} /></View><View className="ml-3 flex-1"><Text className="font-bold text-white">{hook.name}</Text><Text className="mt-1 text-xs text-slate-400" numberOfLines={1}>{hook.url}</Text><Text className="mt-2 text-xs text-sky-300">{hook.events?.join(" · ")}</Text><Text className={`mt-3 text-xs ${hook.lastError ? "text-rose-300" : "text-slate-500"}`} numberOfLines={1}>{hook.lastError ? `Last delivery: ${hook.lastError}` : hook.lastTriggeredAt ? `Last sent: ${new Date(hook.lastTriggeredAt).toLocaleString()}` : "Waiting for its first event"}</Text></View><View className="items-end"><Switch value={hook.isActive} trackColor={{ false: "#334155", true: "#0284c7" }} onValueChange={async (isActive) => { try { await updateHook({ id: hook.id, isActive }).unwrap(); refetchHooks(); } catch (e) { error("Webhook not updated", e); } }} /><TouchableOpacity className="mt-4 p-1" onPress={() => confirm("Delete this webhook?", async () => { await deleteHook(hook.id).unwrap(); await refetchHooks(); })}><MaterialIcons name="delete-outline" size={21} color="#fb7185" /></TouchableOpacity></View></View></Card>) : <Empty icon="hub" title="No webhooks yet" text="Create one to notify accounting, delivery, or e-commerce services." action="Create webhook" onPress={() => open("webhook")} />}</> : <><Section title="Server credentials" text="Create a distinct credential for each trusted server." add="Add key" onPress={() => open("key")} />{keysLoading ? <Loading /> : keys.length ? keys.map((key: any) => <Card key={key.id} className="mb-3"><View className="flex-row items-start"><View className="rounded-2xl bg-violet-400/15 p-2.5"><MaterialIcons name="key" size={20} color="#c4b5fd" /></View><View className="ml-3 flex-1"><Text className="font-bold text-white">{key.name}</Text><Text className="mt-1 font-mono text-xs text-slate-400" numberOfLines={1}>{key.key}</Text><Text className="mt-2 text-xs text-slate-500">{key.lastUsedAt ? `Last used ${new Date(key.lastUsedAt).toLocaleDateString()}` : "Not used yet"}</Text></View><TouchableOpacity className="p-1" onPress={() => confirm("Revoke this API key?", async () => { await deleteKey(key.id).unwrap(); await refetchKeys(); })}><MaterialIcons name="delete-outline" size={21} color="#fb7185" /></TouchableOpacity></View></Card>) : <Empty icon="key" title="No API keys yet" text="Create a unique key for each trusted server integration." action="Create API key" onPress={() => open("key")} />}</>}
  </ScrollView>
  <Modal visible={modal === "webhook" || modal === "key"} transparent animationType="slide" onRequestClose={() => setModal(null)}><View className="flex-1 justify-end bg-black/60"><View className="rounded-t-3xl bg-slate-900 p-6"><Text className="text-xl font-black text-white">{modal === "webhook" ? "Create webhook" : "Create API key"}</Text><Text className="mt-1 text-xs text-slate-400">{modal === "webhook" ? "Your server receives selected POS events." : "Create one key per trusted server."}</Text><Label text="Name" /><Input value={name} change={setName} placeholder={modal === "webhook" ? "Accounting sync" : "Finance service"} />{modal === "webhook" && <><Label text="Destination URL" /><Input value={url} change={setUrl} placeholder="https://api.example.com/pos-events" /><Label text="Signing secret (recommended)" /><Input value={secret} change={setSecret} placeholder="Private shared secret" secret /><Text className="mt-2 text-xs leading-5 text-slate-500">POS sends an HMAC signature in <Text className="font-mono text-slate-400">X-POS-Signature</Text>. Verify it before trusting data.</Text><Label text="Send these events" /><View className="flex-row flex-wrap gap-2">{EVENTS.map(([event, detail]) => <TouchableOpacity key={event} onPress={() => setEvents((old) => old.includes(event) ? old.filter((item) => item !== event) : [...old, event])} className={`rounded-2xl border px-3 py-2.5 ${events.includes(event) ? "border-sky-400 bg-sky-500/15" : "border-white/10 bg-slate-950"}`}><Text className={`text-xs font-bold ${events.includes(event) ? "text-sky-300" : "text-slate-400"}`}>{event}</Text><Text className="mt-0.5 text-[10px] text-slate-500">{detail}</Text></TouchableOpacity>)}</View></>}<TouchableOpacity disabled={hookState.isLoading || keyState.isLoading} className={`mt-6 rounded-2xl py-4 ${modal === "webhook" ? "bg-sky-400" : "bg-violet-400"}`} onPress={() => void submit()}><Text className="text-center font-black text-slate-950">{hookState.isLoading || keyState.isLoading ? "Creating…" : "Create"}</Text></TouchableOpacity></View></View></Modal>
  <Modal visible={modal === "guide"} transparent animationType="slide" onRequestClose={() => setModal(null)}><View className="flex-1 justify-end bg-black/60"><View className="max-h-[86%] rounded-t-3xl bg-slate-900 p-6"><View className="mb-4 flex-row justify-between"><Text className="text-xl font-black text-white">Integration guide</Text><TouchableOpacity onPress={() => setModal(null)}><MaterialIcons name="close" size={24} color="#94a3b8" /></TouchableOpacity></View><ScrollView><Guide n="1" t="Choose the connection" d="Webhooks notify your server automatically. API keys let a trusted server call POS APIs." /><Guide n="2" t="Create a secure webhook" d="Use an HTTPS URL you control, choose only necessary events, and set a long random signing secret." /><Guide n="3" t="Verify every request" d="Check the HMAC-SHA256 X-POS-Signature against the raw JSON request body before processing it." /><Guide n="4" t="Keep secrets on your server" d="Copy API secrets once and store them in an environment variable or secret manager. Never put them in a mobile app or browser." /><Guide n="5" t="Monitor delivery" d="Cards show the latest delivery result. Fix endpoint errors, then enable the webhook again." /></ScrollView></View></View></Modal>
  </SafeAreaView></Screen>;
}
function Section({ title, text, add, onPress }: { title: string; text: string; add: string; onPress: () => void }) { return <View className="mb-3 flex-row items-end justify-between"><View className="flex-1 pr-3"><Text className="text-base font-black text-white">{title}</Text><Text className="mt-1 text-xs text-slate-400">{text}</Text></View><TouchableOpacity className="rounded-xl bg-sky-400 px-3 py-2.5" onPress={onPress}><Text className="font-bold text-slate-950">{add}</Text></TouchableOpacity></View>; }
function Empty({ icon, title, text, action, onPress }: { icon: keyof typeof MaterialIcons.glyphMap; title: string; text: string; action: string; onPress: () => void }) { return <Card className="items-center py-8"><MaterialIcons name={icon} size={28} color="#94a3b8" /><Text className="mt-4 font-bold text-white">{title}</Text><Text className="mt-2 text-center text-xs leading-5 text-slate-400">{text}</Text><TouchableOpacity className="mt-5 rounded-xl bg-sky-500/15 px-4 py-2.5" onPress={onPress}><Text className="font-bold text-sky-300">{action}</Text></TouchableOpacity></Card>; }
function Loading() { return <Text className="py-8 text-center text-slate-500">Loading…</Text>; } function Label({ text }: { text: string }) { return <Text className="mb-2 mt-4 text-xs font-bold uppercase tracking-widest text-slate-400">{text}</Text>; } function Input({ value, change, placeholder, secret }: { value: string; change: (v: string) => void; placeholder: string; secret?: boolean }) { return <TextInput value={value} onChangeText={change} placeholder={placeholder} placeholderTextColor="#64748b" autoCapitalize="none" autoCorrect={false} secureTextEntry={secret} className="rounded-2xl border border-white/10 bg-slate-950 px-4 py-3.5 text-white" />; } function Guide({ n, t, d }: { n: string; t: string; d: string }) { return <View className="mb-5 flex-row"><View className="h-7 w-7 items-center justify-center rounded-full bg-sky-500/15"><Text className="text-xs font-black text-sky-300">{n}</Text></View><View className="ml-3 flex-1"><Text className="font-bold text-white">{t}</Text><Text className="mt-1 text-xs leading-5 text-slate-400">{d}</Text></View></View>; }
